version: "3.7"

networks:
  mojaloop-net:
    name: mojaloop-net

services:
  reporting-hub-bop-role-ui:
    container_name: reporting-hub-bop-role-ui
    image: mojaloop/reporting-hub-bop-role-ui
    build:
      context: .
      cache_from:
        - mojaloop/reporting-hub-bop-role-ui
      args:
        - PUBLIC_PATH=http://localhost:3012/
        - ROLE_API_URL=http://localhost:3008/
    ports:
      - "3012:3012"
    networks:
      - mojaloop-net
    healthcheck:
      test: wget -q http://172.17.0.1:3012 -O /dev/null || exit 1
      timeout: 20s
      retries: 30
      interval: 15s
